"""initial migration

Revision ID: 08cc99db2374
Revises: None
Create Date: 2016-02-22 23:46:05.467000

"""

# revision identifiers, used by Alembic.
revision = '08cc99db2374'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=mysql.CHAR(length=20),
               nullable=True)
    op.create_unique_constraint(None, 'roles', ['name'])
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.alter_column('roles', 'name',
               existing_type=mysql.CHAR(length=20),
               nullable=False)
    ### end Alembic commands ###
